name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    name: Lint

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install --no-install-recommends -y python3-pip && python3 -m pip install -U flake8 yapf
    - name: flake8
      run: python3 -m flake8
    - name: yapf
      run: python3 -m yapf -d -r .
