name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Unit Test

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Deps
      run: |
        apt update
        apt install --no-install-recommends -y \
            make \
            git \
            python3-dev \
            python3-pip \
            valgrind
        python3 -m pip install -U \
            alephzero \
            pip \
            wheel \
            setuptools \
            pytest \
            pytest-asyncio \
            requests \
            websockets==9.1
    - name: Build API
      run: make bin/api -j DEBUG=1
    - name: Run Test
      run: python3 -m pytest test/test_api.py

  lint:
    name: Lint

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: |
        apt update
        apt install --no-install-recommends -y clang-format git python3-pip
        python3 -m pip install -U flake8 yapf
    - name: flake8
      run: python3 -m flake8
    - name: yapf
      run: python3 -m yapf -d -r .
    - name: clang-format
      run: |
        find . -name '*.[ch]pp' | xargs \
          clang-format -i --style=file --verbose
        git --no-pager diff --exit-code

  docker:
    name: Push Docker

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Log into GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build & Push Latest
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ghcr.io/alephzero/api:latest
    - name: Build & Push Tag
      if: startsWith(github.ref, 'refs/tags')
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ghcr.io/alephzero/api:${{ steps.tagname.outputs.tag }}
