name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Unit Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build API
      run: docker build -t alephzero_api --build-arg=mode=cov .
    - name: Build API Test
      run: docker build -t alephzero_api_test -f test/Dockerfile .
    - name: Run Test
      run: docker run --rm -it alephzero_api_test
    # TODO(lshamis): Add coverage
    #   run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: Lint

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        apt update
        apt install --no-install-recommends -y clang-format git python3-pip
        python3 -m pip install -U flake8 yapf
    - name: flake8
      run: python3 -m flake8
    - name: yapf
      run: python3 -m yapf -d -r .
    - name: clang-format
      run: |
        shopt -s globstar
        git init
        git config --global user.name "none"
        git config --global user.email "none"
        git add **
        git commit -am "INITIAL STATE"
        clang-format -i --style=file include/** src/** || true
        git --no-pager diff --exit-code
